openapi: "3.0.2"
info:
  title: Generic Deno-CRUD Example App
  version: "1.0"
servers:
  - url: https://localhost:8000/api/v1

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
paths:
  /user/login:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      description: Return user issued JWT
      responses:
        "200":
          description: OK
        "404":
          description: User couldn't found
  /user/register:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                repeatPassword:
                  type: string
      description: Create new user object in DB for user
      responses:
        "200":
          description: OK
        "400":
          description: User already exists
  /user/me:
    get:
      security:
        - BearerAuth: []
      description: Return user data related to JWT
      responses:
        "200":
          description: OK
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          description: User couldn't found
